source 'http://rubygems.org'

gem 'rails', '3.1.1.rc2'
gem 'therubyracer'
# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'
gem 'devise'
gem 'sqlite3'
gem 'country-select', :path => 'vendor/plugins/rails-country-select' #the select country plugin

gem 'json'

#Gem for Facebook authentication
gem "omniauth-facebook" 

#Gem for Twitter authentication
gem 'omniauth-twitter'

#Gem for Github authentication
gem 'omniauth-github'

#Gem for integration form_for tag with Bootstrap
gem 'twitter_bootstrap_form_for'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.0'
  gem 'coffee-rails', '~> 3.1.0'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', "~>1.0.19"

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

